import 0.9.6

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -1,16 +1,16 @@
 #!/bin/sh
 # ** (c) 2015/16 TosoBoso - common lib for Kopano-4-Synology in Docker container
 # ** set environment
-VER_COMMUNITY_BASE_TAG="Community_base-8.6.81_Web-3.4.21_Push-2.4.4"
-VER_SUPPORTED_BASE_TAG="Supported_base-8.6.6_Web-3.4.20_Push-2.4.4"
-VER_COMMUNITY_FULL_TAG="Community-8.6.81_Web-3.4.20_Push-2.4.4_Meet-0.29.5_Mmost-5.1.0_Files-2.1.5_Docs-5.4"
-VER_SUPPORTED_FULL_TAG="Supported-8.6.6_Web-3.4.20_Push-2.4.4_Meet-0.29.5_Mmost-5.1.0_Files-2.1.4_Docs-5.4"
+VER_COMMUNITY_BASE_TAG="Community_base-8.7.80_Web-3.5.1_Push-2.4.5"
+VER_SUPPORTED_BASE_TAG="Supported_base-8.6.9_Web-3.5.0_Push-2.4.5"
+VER_COMMUNITY_FULL_TAG="Community-8.7.80_Web-3.5.1_Push-2.4.5_Meet-0.29.5_Mmost-5.6.1_Files-2.1.5_Docs-5.4"
+VER_SUPPORTED_FULL_TAG="Supported-8.6.9_Web-3.5.0_Push-2.4.5_Meet-0.29.5_Mmost-5.6.1_Files-2.1.4_Docs-5.4"
 VER_MIGRATION_TAG="Migration-8.4.5.0_Web-3.4.2_Push-2.3.9"
-COMMUNITY_BASE_SIZE=153
-SUPPORTED_BASE_SIZE=139
-MIGRATION_SIZE=140
-COMMUNITY_FULL_SIZE=171
-SUPPORTED_FULL_SIZE=157
+COMMUNITY_BASE_SIZE=155
+SUPPORTED_BASE_SIZE=151
+MIGRATION_SIZE=150
+COMMUNITY_FULL_SIZE=174
+SUPPORTED_FULL_SIZE=169
 PKG_NAME=Kopano4s
 ETC_PATH="/usr/syno/etc/packages/$PKG_NAME"
 TARGET_PATH="/var/packages/$PKG_NAME/target"
@@ -175,7 +175,7 @@ CHECK_DOWNLOAD_SOURCE()
 # ** find if tag exists on docker hub repository url
 CHECK_DOCKER_TAG()
 {
-	local URL="$1"
+	local URL="https://registry.hub.docker.com/v2/repositories/$1/tags/"
 	local TAG="$2"
 	# ** check if the url is valid
 	if ! curl -Is $URL | head -n 1 | grep -q OK
@@ -183,14 +183,16 @@ CHECK_DOCKER_TAG()
 		echo "URL $URL does not exist"
 		return 1
 	fi
-	# ** grep tag out of index.htm stream
+	# ** grep tag out of js stream
 	if [ ! -n $TAG ]
 	then
-		echo "tag $TAG is empty"		
+		echo "tag $TAG is empty"
 		return 1
 	fi
-	if curl --silent $URL | grep -q $TAG
+	if curl --silent $URL | jq '."results"[]["name"]' | grep -q $TAG
+
 	then
+		#echo "Tag found $TAG"		
 		return 0
 	else
 		#echo "Tag $TAG does not exist"
@@ -247,9 +249,7 @@ GET_K4S_SIZE()
 		else
 			K4S_SIZE=$SUPPORTED_BASE_SIZE
 		fi
-	fi
-	if [ "$K_EDITION" == "Community" ]
-	then
+	else
 		if [ "$K_SIZE" == "FULL" ] 
 		then
 			K4S_SIZE=$COMMUNITY_FULL_SIZE
@@ -267,6 +267,7 @@ GET_WIZZARD_CFG()
 	# ** set defaults for non wizzard settings
 	# Careful K_REPLICATION is set below for master and then set off
 	K_REPLICATION_PWD=""
+	K_SEARCH="OFF"
 	K_MONITOR="OFF"
 	K_POSTGREY="OFF"
 	K_FETCHMAIL="OFF"
@@ -303,6 +304,12 @@ GET_WIZZARD_CFG()
 		DOCKER_NW="host"
 	else
 		DOCKER_NW="bridge"
+	fi
+	if [ "$PKGWIZ_K_SEARCH" == "true" ]
+	then
+		K_SEARCH="ON"
+	else
+		K_SEARCH="OFF"
 	fi
 	if [ "$PKGWIZ_K_GATEWAY_ICAL" == "true" ]
 	then
@@ -391,7 +398,8 @@ GET_WIZZARD_CFG()
 	then
 		K_AMAVISD="ON"
 		K_CLAMAVD="ON"
-		K_SPAMD="ON"
+		# keep K_SPAMD off and only enable by GUI as feature
+		K_SPAMD="OFF"
 	else
 		K_AMAVISD="OFF"
 		K_CLAMAVD="OFF"
@@ -474,29 +482,33 @@ GET_DOWNLOAD_REL_NR()
 	set +f; unset IFS
 	RET_REL_MAJ="${1}.${2}.${3}"
 }
+GET_DOCKER_TAGS()
+{
+	# taken from http://www.googlinux.com/list-all-tags-of-docker-image/ skipping library 
+	# e.g. curl --silent https://registry.hub.docker.com/v2/repositories/tosoboso/kopano4s/tags/ | jq '."results"[]["name"]'
+	local URL="https://registry.hub.docker.com/v2/repositories/$1/tags/"
+	echo "tags in $1:"
+	curl --silent $URL | jq '."results"[]["name"]'
+}
 # ** find the latest tag on docker hub repository url
-GET_DOCKER_TAG()
+GET_DOCKER_TAG1()
 {
 	if [ ! -n "$1" ]
 	then
-		echo "URL is empty"		
+		echo "Repository argument empty"		
 		return 1
 	fi
-	local URL="$1"
+	local URL="https://registry.hub.docker.com/v2/repositories/$1/tags/"
 	if [ ! -n "$2" ]
 	then
-		echo "Edition is empty"		
+		echo "Edition tag is empty"		
 		return 1
 	fi
-	local EDTAG=">${2}-[[:graph:]]*<"
+	local EDTAG="${2}-[[:graph:]]*"
 	# ** check if the url is valid
-	if ! curl -Is $URL | head -n 1 | grep -q OK
-	then
-		echo "URL $URL does not exist"
-		return 1
-	fi
 	# we grep for the tag in <> and then remove the signs; 1st > then <
-	RET_VER_TAG=`curl --silent $URL | grep -o $EDTAG | head -1 | cut -f2 -d \> | cut -f1 -d \<`
+	#RET_VER_TAG=`curl --silent $URL | grep -o $EDTAG | head -1 | cut -f2 -d \> | cut -f1 -d \<`
+	RET_VER_TAG=`curl --silent $URL | jq '."results"[]["name"]' | grep -o $EDTAG | head -1 | cut -f1 -d '"'`
 	if [ -n "$RET_VER_TAG" ]
 	then
 		return 0
@@ -505,7 +517,7 @@ GET_DOCKER_TAG()
 		return 1
 	fi
 }
-# calls GET_DOCKER_TAG and sets latest tag from repository or by fallback the version as of spk date
+# calls GET_DOCKER_TAG1 and sets latest tag from repository or by fallback the version as of spk date
 GET_VER_TAG()
 {
 	# if no package cfg exist get edition from PKGWIZ during install
@@ -519,7 +531,7 @@ GET_VER_TAG()
 	fi
 	if [ "$K_EDITION" == "Supported" ]
 	then
-		# set defaults from SPK in case GET_DOCKER_TAG fails
+		# set defaults from SPK in case GET_DOCKER_TAG1 fails
 		if [ "$K_SIZE" == "FULL" ] 
 		then
 			EDITION="Supported"
@@ -531,7 +543,7 @@ GET_VER_TAG()
 	fi
 	if [ "$K_EDITION" == "Community" ]
 	then
-		# set defaults from SPK in case GET_DOCKER_TAG fails
+		# set defaults from SPK in case GET_DOCKER_TAG1 fails
 		if [ "$K_SIZE" == "FULL" ] 
 		then
 			EDITION="Community"
@@ -544,9 +556,9 @@ GET_VER_TAG()
 	if [ "$K_EDITION" == "Migration" ]
 	then
 		VER_TAG=$VER_MIGRATION_TAG
-		# no need to do GET_DOCKER_TAG
+		# no need to do GET_DOCKER_TAG1
 	else
-		if GET_DOCKER_TAG "https://$K_DHUB" $EDITION
+		if GET_DOCKER_TAG1 "tosoboso/kopano4s" $EDITION
 		then
 			# found latest version so use it
 			VER_TAG=$RET_VER_TAG
@@ -705,7 +717,13 @@ DOWNL_PRE_CHECK()
 	then
 		DOWNLOAD_SOURCE="https://$K_URL_COM/core:/"
 	else
-		K_SNR=$PKGWIZ_K_SNR
+		if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]
+		then
+			K_SNR=$PKGWIZ_K_SNR
+		else
+			# get K_SNR from package-cfg
+			. "$ETC_PATH"/package.cfg
+		fi
 		DOWNLOAD_SOURCE="https://serial:${K_SNR}@${K_URL_SUP}/core:/"
 	fi
 	if [ "$PKGWIZ_BUILD" == "true" ]
@@ -728,7 +746,7 @@ DOWNL_PRE_CHECK()
 			GUI_MESSAGE "Fatal Error: Docker-Hub unavailable $K_DHUB "
 			exit 1
 		fi	
-		if ! CHECK_DOCKER_TAG "https://$K_DHUB" $VER_TAG
+		if ! CHECK_DOCKER_TAG tosoboso/kopano4s $VER_TAG
 		then
 			NOTIFY_MESSAGE "Warning: Tag $VER_TAG not found on Docker-Hub for tosoboso/kopano4s"
 			exit 0
@@ -794,6 +812,21 @@ INIT_UPDATE()
 		AUSRID=`id -u k4samavis`
 		echo -e "$AUSRID" > $ETC_PATH/kopano/auid
 	fi
+	# attachments on fs in sync with pkg-cfg as it was set wrong in earlier versions
+	if grep "^attachment_storage" /etc/kopano/server.cfg | grep -q files
+	then
+		ATTACHMENT_ON_FS="ON"
+	else
+		ATTACHMENT_ON_FS="OFF"
+	fi
+	# disable coredump in server.log to avoid log warnings and issues
+	if grep -q "#coredump_enabled" /etc/kopano/server.cfg
+	then
+		sed -i -e "s~#coredump_enabled.*~coredump_enabled = no~" /etc/kopano/server.cfg
+		sed -i -e "s~#coredump_enabled.*~coredump_enabled = no~" /etc/kopano/server.cfg.init
+	fi
+	# init K_SEARCH by enabled when it did not exist aka is empty (! -n)
+	if [ ! -n "$K_SEARCH" ] ; then K_SEARCH="ON" ; fi
 	# amavis now holds spamassasin and clamav in same directory and soft links are used in container
 	if [ -e $K_SHARE/spamassasin ] ; then rm $K_SHARE/spamassasin ; fi
 	if [ -e $K_SHARE/clamav ] ; then rm $K_SHARE/clamav ; fi
@@ -971,7 +1004,7 @@ SET_CFG_OPTIONS()
 	fi
 	if [ "$ATTACHMENT_ON_FS" == "ON" ]
 	then
-		sed -i -e "s~attachment_storage	= database~attachment_storage	= files~" $TARGET_PATH/merge/server.cfg.init
+		sed -i -e "s~attachment_storage.*~attachment_storage	= files~" $TARGET_PATH/merge/server.cfg.init
 		if [ "$K_EDITION" == "Migration" ]
 		then
 			GUI_MESSAGE "Note attachment seetings need to be setup from scratch. When importing old Zarafa database with attachments on FS the strict mode will force no startup. See admin-manual regarding migration."
@@ -1123,6 +1156,12 @@ SET_OPTIONALS()
 {
 	# ** change kopano-etc-default entry to enable optional services
 	if [ "$K_EDITION" == "Supported" ] ; then $SUDO sed -i -e 's~SUPPORTED.*~SUPPORTED=yes~' $ETC_PATH/kopano/default.init ; fi
+	if [ "$K_SEARCH" == "OFF" ]
+	then
+		$SUDO sed -i -e 's~SEARCH_ENABLED.*~SEARCH_ENABLED=no~' $ETC_PATH/kopano/default.init
+		if grep -q "^#search_enabled" $ETC_PATH/kopano/server.cfg.init ; then $SUDO sed -i -e 's~#search_enabled~search_enabled~' $ETC_PATH/kopano/server.cfg.init ; fi
+		$SUDO sed -i -e 's~search_enabled.*~search_enabled = no~' $ETC_PATH/kopano/server.cfg.init
+	fi
 	if [ "$K_MONITOR" == "ON" ] ; then $SUDO sed -i -e 's~MONITOR_ENABLED.*~MONITOR_ENABLED=yes~' $ETC_PATH/kopano/default.init ; fi
 	if [ "$K_GATEWAY" == "ON" ] ; then $SUDO sed -i -e 's~GATEWAY_ENABLED.*~GATEWAY_ENABLED=yes~' $ETC_PATH/kopano/default.init ; fi
 	if [ "$K_ICAL" == "ON" ] ; then $SUDO sed -i -e 's~ICAL_ENABLED.*~ICAL_ENABLED=yes~' $ETC_PATH/kopano/default.init ; fi
@@ -1240,6 +1279,7 @@ SET_PKG_CFG()
 		echo K_SYNC_SYNOCERT="\"$K_SYNC_SYNOCERT\""
 		echo K_REPLICATION="\"$K_REPLICATION\""
 		echo K_REPLICATION_PWD="\"$K_REPLICATION_PWD\""
+		echo K_SEARCH="\"$K_SEARCH\""
 		echo K_MONITOR="\"$K_MONITOR\""
 		echo K_GATEWAY="\"$K_GATEWAY\""
 		echo K_ICAL="\"$K_ICAL\""
@@ -1284,16 +1324,26 @@ SET_PKG_CFG()
 SET_DOCKERFILE()
 {
 	local URL_CORE
+	local URL_UBCORE
 	local VTAG
 	local URL_Z_PUSH="http://repo.z-hub.io/z-push:/final/Debian_9.0/all/"
+	local URL_WEBAPP
+	local URL_MDM
+	local URL_SMIME
+	local URL_UBSMIME
 	local URL_WEBMEET
 	local URL_MATMOST
 	local URL_FILES
 	local URL_DOCED
 	local KED
+	local URL_PASSWD="https://github.com/apio-sys/kopano-webapp-passwd/raw/master/builds/passwd-1.4.zip"
+	# from fork "https://github.com/dducret/kopano-webapp-passwd/raw/master/builds/passwd-1.3.zip"
+	# newer but with issues "https://github.com/apio-sys/kopano-webapp-passwd/raw/master/builds/passwd-1.4.zip"
+	local URL_PFETCHM="https://github.com/olia-dev/kopano-webapp-fetchmail/raw/master/builds/fetchmail-1.0.2.zip"
 	if [ "$K_EDITION" == "Supported" ]
 	then
 		URL_CORE="${K_URL_SUP}/core:/final/Debian_9.0"
+		URL_UBCORE="${K_URL_SUP}/core:/final/Ubuntu_18.04/amd64"
 		GET_K_DOWNLOAD_BY_TAG "https://serial:${K_SNR}@${URL_CORE}/all/" "kopano-server-packages_"
 		GET_DOWNLOAD_REL_NR "https://serial:${K_SNR}@${RET_URL}" packages all
 		VTAG="Core-${RET_REL}"
@@ -1311,6 +1361,7 @@ SET_DOCKERFILE()
 		URL_MDM="${K_URL_SUP}/mdm:/final/Debian_9.0/all/"
 		GET_K_DOWNLOAD_BY_TAG "https://serial:${K_SNR}@${K_URL_SUP}/smime:/final/tarballs/" "Debian_9.0-amd64.tar.gz"
 		URL_SMIME=$RET_URL
+		URL_UBSMIME="${K_URL_SUP}/smime:/final/Ubuntu_18.04/all"
 		GET_K_DOWNLOAD_BY_TAG $URL_Z_PUSH "z-push-kopano_"
 		GET_DOWNLOAD_REL_NR $RET_URL z-push-kopano all
 		VTAG="${VTAG}_Push-${RET_REL}"
@@ -1353,6 +1404,8 @@ SET_DOCKERFILE()
 		URL_CORE=$RET_URL
 		GET_DOWNLOAD_REL_NR $RET_URL core- -Debian
 		VTAG="Core-${RET_REL}"
+		GET_K_DOWNLOAD_BY_TAG "https://$K_URL_COM/core:/" "Ubuntu_18.04-amd64.tar.gz"
+		URL_UBCORE=$RET_URL
 		if [ "$K_SIZE" == "FULL" ] 
 		then
 			VER_TAG="Community-${RET_REL_MAJ}"
@@ -1368,6 +1421,8 @@ SET_DOCKERFILE()
 		URL_MDM=$RET_URL
 		GET_K_DOWNLOAD_BY_TAG "https://$K_URL_COM/smime:/" "Debian_9.0-amd64.tar.gz"
 		URL_SMIME=$RET_URL
+		GET_K_DOWNLOAD_BY_TAG "https://$K_URL_COM/smime:/" "Ubuntu_18.04-amd64.tar.gz"
+		URL_UBSMIME=$RET_URL
 		GET_K_DOWNLOAD_BY_TAG $URL_Z_PUSH "z-push-kopano_"
 		GET_DOWNLOAD_REL_NR $RET_URL z-push-kopano all
 		VTAG="${VTAG}_Push-${RET_REL}"
@@ -1432,14 +1487,18 @@ SET_DOCKERFILE()
 	sed -i -e "s~EDITION=.*~EDITION=\"$KED\" \\\ ~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~TAG=.*~TAG=\"$VTAG\" \\\ ~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_CORE~$URL_CORE~" /var/packages/Kopano4s/scripts/Dockerfile
+	sed -i -e "s~G_URL_UBCORE~$URL_UBCORE~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_WEBAPP~$URL_WEBAPP~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_MDM~$URL_MDM~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_SMIME~$URL_SMIME~" /var/packages/Kopano4s/scripts/Dockerfile
+	sed -i -e "s~G_URL_UBSMIME~$URL_UBSMIME~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_Z_PUSH~$URL_Z_PUSH~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_WEBMEET~$URL_WEBMEET~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_MATMOST~$URL_MATMOST~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_FILES~$URL_FILES~" /var/packages/Kopano4s/scripts/Dockerfile
 	sed -i -e "s~G_URL_DOCED~$URL_DOCED~" /var/packages/Kopano4s/scripts/Dockerfile
+	sed -i -e "s~G_URL_PASSWD~$URL_PASSWD~" /var/packages/Kopano4s/scripts/Dockerfile
+	sed -i -e "s~G_URL_PFETCHM~$URL_PFETCHM~" /var/packages/Kopano4s/scripts/Dockerfile
 	# remove kopano-spamd as it did not exist at the time
 	if [ "$K_EDITION" == "Migration" ]
 	then
@@ -1513,7 +1572,7 @@ SET_DOCKER_ENV()
 	DOCKER_PORTS="-p 236:236 -p 237:237 -p 25:25 -p 2003:2003 -p $HTTP_PORT:9080 -p $HTTPS_PORT:9443"
 	if [ "$K_GATEWAY" == "ON" ]
 	then
-		DOCKER_PORTS="$DOCKER_PORTS -p 143:143 -p 993:993"
+		DOCKER_PORTS="$DOCKER_PORTS -p 587:587 -p 143:143 -p 993:993"
 	fi
 	if [ "$K_ICAL" == "ON" ]
 	then
